#!/usr/bin/env python3.8
# Copyright J. Mark Deric, 2020.  All rights reserved

# Note: this is the newer app preamble updated for python3
import os.path, sys, inspect
this_file = os.path.abspath(inspect.getsourcefile((lambda x:x)))
this_dir = os.path.dirname(this_file)
parent_dir = this_dir + '/..'
sys.path.append(parent_dir)
# end: preamble

from covid19_analytics.subcommand_runners import (
    FindActive,
    Jhu2Csv
    )

from argparse import ArgumentParser

def call_runner(cl_args) :
    os.umask(0o002)
    impl = cl_args.run_class(cl_args)
    return impl.run()

if __name__ == '__main__':
    #print(this_dir)
    parser = ArgumentParser()
    subparsers = parser.add_subparsers()

    # parser for the find_active subcommand
    p_start_idea = subparsers.add_parser('find_active')
    p_start_idea.set_defaults(run_class=FindActive)
    p_start_idea.add_argument('-d', '--death-delay',
                              help='Avg. days, symptomatic to death (default: 17)',
                              type=int, default=17)
    p_start_idea.add_argument('-r', '--recover-delay',
                              help='Avg. days, symptomatic to recovery (default: 14)',
                              type=int, default=14)
    p_start_idea.add_argument('-i', '--csv-file',
                              help='CSV input file', type=str, required=True)
    p_start_idea.add_argument('-l', '--log-plot',
                              help='Plot y axis as log', action='store_true')

    # parser for the jhu2csv subcommand
    p_start_idea = subparsers.add_parser('jhu2csv')
    p_start_idea.set_defaults(run_class=Jhu2Csv)
    p_start_idea.add_argument('-w', '--working-data',
                              help='Working data directory', type=str, required=True)

    # generic subcommand execution call
    parsed_args = parser.parse_args()
    #print parsed_args
    exit(call_runner(parsed_args))
