#!/usr/bin/env python3.8
# -*- coding: utf-8 -*-
# Copyright J. Mark Deric, 2020.  All rights reserved

# Note: this is the newer app preamble updated for python3
import os.path, sys, inspect
this_file = os.path.abspath(inspect.getsourcefile((lambda x:x)))
this_dir = os.path.dirname(this_file)
parent_dir = this_dir + '/..'
sys.path.append(parent_dir)
# end: preamble

from covid19_analytics.subcommand_runners import (
    FindActive,
    Jhu2Csv,
    PlotData,
    GetJhuData,
    CreatePlots,
    )

from argparse import ArgumentParser

def call_runner(cl_args) :
    os.umask(0o002)
    impl = cl_args.run_class(cl_args)
    return impl.run()

if __name__ == '__main__':
    #print(this_dir)
    parser = ArgumentParser()
    subparsers = parser.add_subparsers()

    cmds = { 'find_active' : [ FindActive, None ],
             'jhu2csv' : [ Jhu2Csv, None ],
             'plot_data' : [ PlotData, None ],
             'get_data' : [ GetJhuData, None ],
             'create_plots' : [ CreatePlots, None ],
    }
    for cmd in cmds:
        cmds[cmd][1] = subparsers.add_parser(cmd)
        cmds[cmd][1].set_defaults(run_class=cmds[cmd][0])
        cmds[cmd][1].add_argument('-w', '--wrk-dir', type=str, required=True,
                                  help='Working data directory')

    # additional subparser detail
    subp = cmds['find_active'][1]
    subp.add_argument('-r', '--recover-delay',
                      help='Avg. days, positive test to outcome (default: 14)',
                      type=int, default=14)
    subp.add_argument('-f', '--file-stub', type=str, required=True,
                      help='Stub for .csv file and prefix stub for graphs')
    subp = cmds['plot_data'][1]
    subp.add_argument('-f', '--file-stub', type=str, required=True,
                      help='Stub for .csv file and prefix stub for graphs')
    subp = cmds['get_data'][1]
    subp.add_argument('-R', '--jhu-repo', type=str, required=True,
                      help='Path to the Johns Hopkins covid git repo')
    subp.add_argument('-d', '--json-data-list', type=str, required=True,
                      help='Path to the json data list file')
    subp = cmds['create_plots'][1]
    subp.add_argument('-r', '--recover-delay',
                      help='Avg. days, positive test to outcome (default: 14)',
                      type=int, default=14)
    group = subp.add_mutually_exclusive_group(required=True)
    group.add_argument('-f', '--file-stub', type=str,
                       help='Stub for .csv file and prefix stub for graphs')
    group.add_argument('-j', '--use-json', action='store_true',
                       help='Use the state.json file for plots to create')

    # generic subcommand execution call
    parsed_args = parser.parse_args()
    #print parsed_args
    exit(call_runner(parsed_args))
