#!/usr/bin/env python3.8
# Copyright J. Mark Deric, 2020.  All rights reserved

# Note: this is the newer app preamble updated for python3
import os.path, sys, inspect
this_file = os.path.abspath(inspect.getsourcefile((lambda x:x)))
this_dir = os.path.dirname(this_file)
parent_dir = this_dir + '/..'
sys.path.append(parent_dir)
# end: preamble

from covid19_analytics.subcommand_runners import (
    FindActive,
    Jhu2Csv,
    PlotData,
    )

from argparse import ArgumentParser

def call_runner(cl_args) :
    os.umask(0o002)
    impl = cl_args.run_class(cl_args)
    return impl.run()

if __name__ == '__main__':
    #print(this_dir)
    parser = ArgumentParser()
    subparsers = parser.add_subparsers()

    cmds = { 'find_active' : [ FindActive, None ],
             'jhu2csv' : [ Jhu2Csv, None ],
             'plot_data' : [ PlotData, None ],
    }
    for cmd in cmds:
        cmds[cmd][1] = subparsers.add_parser(cmd)
        cmds[cmd][1].set_defaults(run_class=cmds[cmd][0])
        cmds[cmd][1].add_argument('-w', '--wrk-dir', type=str, required=True,
                                  help='Working data directory')

    # additional subparser detail
    subp = cmds['find_active'][1]
    subp.add_argument('-r', '--recover-delay',
                      help='Avg. days, symptomatic to recovery (default: 14)',
                      type=int, default=14)

    # generic subcommand execution call
    parsed_args = parser.parse_args()
    #print parsed_args
    exit(call_runner(parsed_args))
